apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/enterprise-contract/enterprise-contract-controller/config/crd?ref=da2c6820c59a9558b69e75e79bffea0d3d0f4a13
  - ecp.yaml
  - role.yaml
  - rolebinding.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/enterprise-contract/ec-task-bundle:b49422d08a3f06e50f08b3536336f815814915fa@sha256:ddfb257f15245f53ac40b01e65013b450aee026a205723957e758ea913cf7400
      - verify_ec_task_git_url=https://github.com/enterprise-contract/ec-cli.git
      - verify_ec_task_git_revision=b49422d08a3f06e50f08b3536336f815814915fa
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
