apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/hacbs-contract/enterprise-contract-controller/config/crd?ref=e900a4e7b0a7ee31e5fe890d05abac15680b1534
  # Kustomize does not allow github.com urls that reference a single-file. They must always reference
  # a directory that contains a kustomization.yaml file. The directory /config/rbac does include a
  # kustomization.yaml file but it includes many other RBAC changes that are not desirable here. Use
  # a URL to the "raw" version of the file instead.
  - https://raw.githubusercontent.com/hacbs-contract/enterprise-contract-controller/e900a4e7b0a7ee31e5fe890d05abac15680b1534/config/rbac/enterprisecontractpolicy_viewer_role.yaml
  - https://raw.githubusercontent.com/hacbs-contract/enterprise-contract-controller/e900a4e7b0a7ee31e5fe890d05abac15680b1534/config/rbac/enterprisecontractpolicy_editor_role.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/hacbs-contract/ec-task-bundle:741b8a1fd9a3e1019e494d5136000aefde10c590@sha256:eb0cd5e3978c372bc82a5e0ab34d7d4d9c74ef1d18d6ef424ea15d1c0e881d44
      - ec_policy_source=oci::https://quay.io/hacbs-contract/ec-release-policy:git-d96c996@sha256:e901dfb01b509372f498344f04a5efd7beef558df9e330ac5af722ee4b6959a3
      - ec_data_source=oci::https://quay.io/hacbs-contract/ec-policy-data:git-d96c996@sha256:03f015d7206d4d40404059e5f4bab2e75510b4a8ac225d57d63635ba52c9addf
images:
  - name: quay.io/redhat-appstudio/enterprise-contract-controller
    newName: quay.io/redhat-appstudio/enterprise-contract-controller
    newTag: e900a4e7b0a7ee31e5fe890d05abac15680b1534
